### ISSUE TITLE
Google API token compromised 

### ISSUE THREAD

**Issue by g4brielvs** [worldbank/pacific-observatory#6]
The Google API token relative to the proposal [Pacific Observatory Tourism Tracker](https://portal.datapartnership.org/readableproposal/399) is [compromised](https://github.com/worldbank/pacific-observatory/blob/7790d12a5b8a525e2b349d886a423f01d0fc48b9/scripts/notebooks/GoogleTrends.ipynb) and has been revoked by the [Development Data Partnership](https://datapartnership.org). To learn how to securely use API keys (or secrets), you may refer to [this example on the World Bank Project Template](https://worldbank.github.io/template/notebooks/nasa-apod.html) or on the [Development Data Partnership Documentation](https://docs.datapartnership.org/partners/google/examples/google-health-trends-api.html). Also, for the project settings, I'd strongly encourage to use [python-dotenv](https://pypi.org/project/python-dotenv) instead of `config.py` to increase reproducibility. 

Please reach out to datapartnership@worldbank.org in case of any questions.

**Comment by g4brielvs** [comment]
@ccxzhang @andresfchamorro Opening this issue about the compromised Google API token. I can't add **assignees** or **labels**.

**Comment by g4brielvs** [comment]
@ccxzhang It was awesome to catch up with you yesterday! In case you would like a new API key, please submit a request to datapartnership@worldbank.org and we will be able to send it to you.

**Comment by ccxzhang** [comment]
It is closed with a request for a new API key.
